# Generated by Django 5.0.3 on 2024-04-07 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUniversidad', '0002_alumno_profesor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='alumno',
            new_name='nombre',
        ),
    ]
