# Generated by Django 5.0.3 on 2024-04-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUniversidad', '0004_remove_alumno_curso_remove_profesor_curso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='nombre',
            new_name='alumno_id',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='cursos',
            new_name='curso_id',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='nombre',
            new_name='profesor_id',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='cursos',
        ),
        migrations.AddField(
            model_name='profesor',
            name='curso_id',
            field=models.ManyToManyField(to='AppUniversidad.curso'),
        ),
    ]
