# Generated by Django 5.0.3 on 2024-05-01 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUniversidad', '0005_rename_nombre_alumno_alumno_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='curso_id',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='curso_id',
        ),
        migrations.AddField(
            model_name='alumno',
            name='curso_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppUniversidad.curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='curso_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='AppUniversidad.curso'),
            preserve_default=False,
        ),
    ]
